name: Java CI

on: [push]

jobs:
  build:
    runs-on: groovy:3.0.10-jdk11
    timeout-minutes: 90

    steps:
      - name: Build with Gradle
        run: ./gradlew dist -x test
        #      - name: Run Unit Tests
        #run: ./gradlew test
      - name: Execute Functional Tests
        run: cd tests && ./run.sh          
